# Generated by Django 4.2.1 on 2023-05-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
                          
                          INSERT INTO store_collection (title) VALUES   
                          ('collection1') 
                          ""","""
                          
                          DELETE FROM store_collection 
                          where title='collection1'
                          """)
    ]
